### ISSUE TITLE
[feat] notification 설정

### ISSUE THREAD

**Issue by 2dilution2** [ThinkTank-Unit/66Days-server#20]
## 📌 설명
> notification 설정

## 🗒️ Todo
- [ ] notification enum 설정
- [ ] notification dto 설정
- [ ] notification repository 설정
- [ ] notification service 설정
