### ISSUE TITLE
[feat] 엔티티 구현

### ISSUE THREAD

**Issue by 2dilution2** [ThinkTank-Unit/66Days-server#3]
## 📌 설명
> Users, Habit, HabitTracking, Notification 엔티티 구현

## 🗒️ Todo
- [ ] BaseTime 구현
- [ ] Users 엔티티 구현
- [ ] Habit 엔티티 구현
- [ ] HabitTracking 엔티티 구현
- [ ] Notification 엔티티 구현
